pipeline {
    agent any
    environment {
        CI = 'true'
    }
    stages {
        stage('Dependecies') {
            steps {
                sh 'npm install next@latest react@latest react-dom@latest'
            }
        }
        // stage('Test') {
        //     steps {
        //         sh './jenkins/scripts/test.sh'
        //     }
        // }
        stage('Build') {
            steps {
                sh 'next build'
            }
        }
         stage('Deliver') {
            steps {
                sh 'next start'
            }
        }
    }
}
